# frozen_string_literal: true

require_relative '../lib/board'

describe Board do
  describe '#from_fen_parser' do
    subject { described_class }

    let(:fen_parser) { double('fen_parser', construct_squares: squares) }
    let(:squares) { { 1 => [square, square, square] } }
    let(:square) { double('square') }

    it 'sends the message to the fen parser to construct the squares' do
      described_class.from_fen_parser(fen_parser)
      expect(fen_parser).to have_received(:construct_squares)
    end

    it 'returns a board object' do
      result = described_class.from_fen_parser(fen_parser)
      expect(result).to be_a(described_class)
    end

    it 'the board object is constructed with the squares generated by the fen parser' do
      result = described_class.from_fen_parser(fen_parser)
      board_squares = result.instance_variable_get(:@squares)
      expect(board_squares).to be(squares)
    end
  end
end
