# frozen_string_literal: true

require_relative '../lib/board'

describe Board do
  describe '#from_fen_parser' do
    subject { described_class }

    let(:fen_parser) { double('fen_parser', construct_squares: squares) }
    let(:squares) { { 1 => [square, square, square] } }
    let(:square) { double('square') }

    it 'sends the message to the fen parser to construct the squares' do
      described_class.from_fen_parser(fen_parser)
      expect(fen_parser).to have_received(:construct_squares)
    end

    it 'returns a board object' do
      result = described_class.from_fen_parser(fen_parser)
      expect(result).to be_a(described_class)
    end

    it 'the board object is constructed with the squares generated by the fen parser' do
      result = described_class.from_fen_parser(fen_parser)
      board_squares = result.instance_variable_get(:@squares)
      expect(board_squares).to be(squares)
    end
  end

  describe '#access_square' do
    subject(:board) { described_class.new(squares) }

    let(:squares) { { 1 => [square, square_b1, square] } }
    let(:square_b1) { double('square_b1') }
    let(:square) { double('square') }

    context 'when passed in bounds coordinates' do
      it 'returns the square at those coordinates' do
        result = board.access_square('b1')
        expect(result).to be(square_b1)
      end
    end

    context 'when passed out of bounds coordinates' do
      it 'returns nil' do
        result = board.access_square('d1')
        expect(result).to be_nil
      end
    end
  end
end
